services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    restart: no
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - timescaledb-data:/home/postgres/pgdata/data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: no
    ports:
      - "3000:3000"
volumes:
  timescaledb-data:
