services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - timescaledb-data:/home/postgres/pgdata/data

volumes:
  timescaledb-data:
