name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Bwah Bwah Bwahhh
      run: |
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi
          rustup target add i686-unknown-linux-gnu
          rustup component add rust-src rust-std --target wasm32-unknown-unknown
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu


    - name: Install wasm-bindgen
      run: |
        wget https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.93/wasm-bindgen-0.2.93-x86_64-unknown-linux-musl.tar.gz
        tar -xvzf wasm-bindgen-0.2.93-x86_64-unknown-linux-musl.tar.gz
        sudo cp wasm-bindgen-0.2.93-x86_64-unknown-linux-musl/wasm-bindgen /usr/local/bin/
        sudo cp wasm-bindgen-0.2.93-x86_64-unknown-linux-musl/wasm-bindgen-test-runner /usr/local/bin/

    # Install wasm-opt
    - name: Install wasm-opt
      run: |
        sudo apt-get update
        sudo apt-get install -y binaryen

    - name: Verify installation
      run: |
        bun --version
        cargo --version
        wasm-bindgen --version
        wasm-opt --version
    - name: build shit
      run: |
        bun i
        bash build.sh
        cargo build --release
    - name: Publish to Cloudflare Pages
      if: github.ref == 'refs/heads/master'
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: 3dd81dce86015003355892e51e89be8d
        projectName: knucklebone
        directory: build
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        wranglerVersion: '3'
    - name: Build And publish docker image to ghcr
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/tricked-dev/knucklebones-core:latest

